import { defineConfig, loadEnv, Plugin } from "vite";
import react from "@vitejs/plugin-react";
import builtins from "builtin-modules";
import { copyFileSync, existsSync } from "fs";
import { resolve } from "path";

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY VITE
if you want to view the source, please visit the github repository of this plugin
*/`;

// Mirrors the previous esbuild behaviour: ship styles.css as a static asset
// (Vite does not generate it) and copy it next to main.js when building into a
// separate plugin directory (dev). In production the output dir is the repo
// root where styles.css already lives, so no copy is needed.
function copyStylesPlugin(outDir: string): Plugin {
  return {
    name: "dendron-bridge-copy-styles",
    buildStart() {
      // Re-run the build when styles.css changes in `--watch` mode.
      this.addWatchFile(resolve(__dirname, "styles.css"));
    },
    closeBundle() {
      const dest = resolve(outDir, "styles.css");
      const src = resolve(__dirname, "styles.css");
      if (resolve(dest) === src) return;
      if (!existsSync(src)) return;
      copyFileSync(src, dest);
      // eslint-disable-next-line no-console
      console.log("[styles] copied styles.css ->", outDir);
    },
  };
}

// Prepend the generated-file banner (rollup's output.banner is not honoured in
// Vite lib mode, so do it explicitly per chunk).
function bannerPlugin(): Plugin {
  return {
    name: "dendron-bridge-banner",
    enforce: "post",
    generateBundle(_options, bundle) {
      for (const file of Object.values(bundle)) {
        if (file.type === "chunk") {
          file.code = `${banner}\n${file.code}`;
        }
      }
    },
  };
}

export default defineConfig(({ mode }) => {
  const prod = mode === "production";
  const env = loadEnv(mode, process.cwd(), "");

  // In dev, output directly to the Obsidian vault so changes are hot-reloaded.
  // Set OBSIDIAN_PLUGIN_DIR in .env to your vault's plugins/dendron-bridge path.
  const outDir = prod ? "." : env.OBSIDIAN_PLUGIN_DIR || "./build";

  return {
    plugins: [react(), ...(prod ? [bannerPlugin()] : []), copyStylesPlugin(outDir)],
    resolve: {
      // Mirror tsconfig `baseUrl: "."` so `src/...` style imports resolve.
      alias: [{ find: /^src\//, replacement: resolve(__dirname, "src") + "/" }],
    },
    build: {
      outDir,
      emptyOutDir: false,
      sourcemap: prod ? false : "inline",
      minify: false,
      target: "es2018",
      cssCodeSplit: false,
      lib: {
        entry: resolve(__dirname, "src/main.ts"),
        formats: ["cjs"],
        fileName: () => "main.js",
      },
      rollupOptions: {
        external: [
          "obsidian",
          "electron",
          "@codemirror/autocomplete",
          "@codemirror/collab",
          "@codemirror/commands",
          "@codemirror/language",
          "@codemirror/lint",
          "@codemirror/search",
          "@codemirror/state",
          "@codemirror/view",
          "@lezer/common",
          "@lezer/highlight",
          "@lezer/lr",
          ...builtins,
        ],
        output: {
          exports: "named",
          inlineDynamicImports: true,
        },
      },
    },
  };
});
